### ISSUE TITLE
any suggestions for eslint problems with this setup?

### ISSUE THREAD

**Issue by ssuess** [Braincoke/starter-vue-web-worker#5]
Hi and thanks for the excellent [article](https://braincoke.fr/blog/2020/03/use-web-workers-with-vue/#vue-code). I have been trying six ways from sunday to integrate some kind of web worker functionality into my vue (with quasar) project, but each technique I have tried has its own issues and downsides. I have tried your technique but it seems that eslint (despite being told to ignore the node_modules folder in my webpack rules) is nonetheless complaining about things (semicolons, double over single quotes, etc) when I try to use your technique. I even tried going into the dist folder for worker-loader and adding `eslint-disable` to every file but that did not take care of all the warnings, and they ALL point to `loader.js` even though the eslint complaints are clearly not in that file.  Do you have any suggestions for how to get this running without these formatting errors that are outside of my code? Thanks!

**Comment by ssuess** [comment]
FYI, i was able to get rid of these adding a file specific item to .eslintignore (`eslint-disable` was not working in the file strangely)

**Comment by Braincoke** [comment]
Hi Stephen,

Thanks for taking the time to post your solution, I hope it'll help someone else passing by.
Your issue is very strange indeed, I was tinkering to see if I could reproduce it.
